apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd   # make sure ArgoCD is installed in this namespace
spec:
  project: default
  source:
    repoURL: 'https://github.com/manudevops726/eks-helm-git-argocd.git'
    targetRevision: main
    path: helm-charts/nginx
    helm:
      releaseName: nginx-app   # optional but good practice
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true   # ensures namespace is created if missing
